events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    upstream embedder {
        server embedder:8001;
    }

    upstream knn_dinov2_small {
        server knn_dinov2_small:8000;
    }

    upstream knn_clip_vitb32_laion2b {
        server knn_clip_vitb32_laion2b:8000;
    }

    server {
        listen 80;
        server_name _;

        client_max_body_size 20m;

        root /usr/share/nginx/html;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }

        location /api/embed/ {
            proxy_pass http://embedder/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_read_timeout 120s;
        }

        location /images/ {
            alias /images/;
        }

        location /api/knn/dinov2_small/ {
            proxy_pass http://knn_dinov2_small/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/knn/clip_vitb32_laion2b/ {
            proxy_pass http://knn_clip_vitb32_laion2b/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

    }
}
